import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { Button, Navbar, Card, Text, Grid, Container, Col, Row, Badge } from "@nextui-org/react";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Navbar>
          <Navbar.Brand>
            <Text b color="inherit" hideIn="xs">
              RepezenDogs
            </Text>
          </Navbar.Brand>
          <Navbar.Content
            enableCursorHighlight
            activeColor="secondary"
            hideIn="xs"
            variant="underline"
          >
            <Navbar.Link isActive href="/">
              Home
            </Navbar.Link>
            <Navbar.Link href="/mint">
              Mint
            </Navbar.Link>
            <Navbar.Link href="/market">
              Market
            </Navbar.Link>
            <Navbar.Link href="/hisotry">
              History
            </Navbar.Link>
          </Navbar.Content>
          <Navbar.Content>
            <Navbar.Link color="inherit" href="#">
              Login
            </Navbar.Link>
          </Navbar.Content>
        </Navbar>

        <Container css={{ py: 100 }}>
          <Grid.Container gap={2}>
            <Grid xs={2}>
              <Card css={{ w: "100%" }}>
                <Card.Header css={{ position: "absolute", zIndex: 1, top: 5 }}>
                  <Col>
                    <Text size={12} weight="bold" transform="uppercase" color="#ffffffAA">
                      Chick
                    </Text>
                  </Col>
                </Card.Header>
                <Card.Body css={{ p: 0 }}>
                  <Card.Image
                    src="https://repezen-dogs.s3.ap-northeast-1.amazonaws.com/image/twitfi-ee27f3a2-e1f3-43ef-9390-8d43c2de1ecb.gif"
                    width="100%"
                    height="100%"
                    alt="Card example background"
                  />
                </Card.Body>
                <Card.Footer
                  isBlurred
                  css={{
                    bgBlur: "#ffffff66",
                    borderTop: "$borderWeights$light solid rgba(255, 255, 255, 0.2)",
                  }}
                >
                  <Grid.Container gap={1}>
                    <Grid xs={12}>
                      <Text color="#000" size={16}>
                        TWITFI-T4BE9M
                      </Text>
                    </Grid>
                    <Grid xs={12}>
                      <Badge color="primary" css={{ mr: 5 }}>LEVEL: E</Badge>
                      <Badge color="primary" css={{ mr: 5 }}>TYPE: Shacho</Badge>
                    </Grid>
                    <Grid xs={12}>
                      <Text css={{ textAlign: 'right' }}>
                        Tequila 10/10
                      </Text>
                    </Grid>
                  </Grid.Container>
                </Card.Footer>
              </Card>
            </Grid>
          </Grid.Container>
        </Container>
      </main>
    </>
  )
}
