import Head from 'next/head'
import {
  Breadcrumbs,
  Box,
  Typography
} from '@mui/material'
import NavigateNextIcon from '@mui/icons-material/NavigateNext'
import { Button, Navbar, Card, Text, Grid, Container, Col, Row, Badge } from "@nextui-org/react"
import DefaultLayout from "@/components/layouts/DefaultLayout"

import type { NextPageWithLayout } from '@/pages/_app'

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Repezen Dogs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container css={{ py: 100 }}>
          <Grid.Container gap={2}>
            <Grid xs={2}>
              <Card css={{ w: "100%" }}>
                <Card.Header css={{ position: "absolute", zIndex: 1, top: 5 }}>
                  <Col>
                    <Text size={12} weight="bold" transform="uppercase" color="#ffffffAA">
                      Chick
                    </Text>
                  </Col>
                </Card.Header>
                <Card.Body css={{ p: 0 }}>
                  <Card.Image
                    src="https://repezen-dogs.s3.ap-northeast-1.amazonaws.com/image/twitfi-ee27f3a2-e1f3-43ef-9390-8d43c2de1ecb.gif"
                    width="100%"
                    height="100%"
                    alt="Card example background"
                  />
                </Card.Body>
                <Card.Footer
                  isBlurred
                  css={{
                    bgBlur: "#ffffff66",
                    borderTop: "$borderWeights$light solid rgba(255, 255, 255, 0.2)",
                  }}
                >
                  <Grid.Container gap={1}>
                    <Grid xs={12}>
                      <Text color="#000" size={16}>
                        TWITFI-T4BE9M
                      </Text>
                    </Grid>
                    <Grid xs={12}>
                      <Badge color="primary" css={{ mr: 5 }}>LEVEL: E</Badge>
                      <Badge color="primary" css={{ mr: 5 }}>TYPE: Shacho</Badge>
                    </Grid>
                    <Grid xs={12}>
                      <Text css={{ textAlign: 'right' }}>
                        Tequila 10/10
                      </Text>
                    </Grid>
                  </Grid.Container>
                </Card.Footer>
              </Card>
            </Grid>
          </Grid.Container>
        </Container>
      </main>
    </>
  )
}

Home.getLayout = function getLayout(page) {
  return (
    <DefaultLayout>
      <Box sx={{ my: 3 }}>
        <Breadcrumbs
          aria-label="breadcrumb"
        >
          <Typography color="text.primary">Home</Typography>
        </Breadcrumbs>
      </Box>
      {page}
    </DefaultLayout>
  )
}

export default Home
